services:
  
  redis:
    image: redis
  
  mosca:
    image: mosca
    build:
      context: ./mosca
    depends_on:
      - redis
    ports:
      - 5000:5000
 
  mosguito:
    image: mosguito
    build:
      context: ./mosguito
    ports:
      - 3000:3000